[package]
name = "duckdb_protobuf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
duckdb = { version = "=0.10.1", features = ["vtab-loadable"] }
duckdb-loadable-macros = "0.1.1"
