[package]
name = "duckdb_protobuf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
duckdb = { version = "=0.10.1", features = ["vtab-loadable", "bundled"] }
duckdb-loadable-macros = "0.1.1"
prost-reflect = "0.13.1"
glob = "0.3.1"
byteorder = "1.5.0"
log = "0.4.21"