#:schema node_modules/wrangler/config-schema.json
name = "duckdb_protobuf_serving"
main = "src/worker.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "duckdb-extensions"

[[routes]]
pattern = "duckdb.0xcaff.xyz"
custom_domain = true
