[package]
name = "duckdb_protobuf"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
duckdb = { version = "1.0.0", features = ["vtab-loadable"] }
duckdb-loadable-macros = "0.1.2"
prost-reflect = "0.14.0"
protobuf = "3.5.0"
glob = "0.3.1"
byteorder = "1.5.0"
log = "0.4.21"
ouroboros = "0.18.4"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.63"
crossbeam = "0.8.4"

[dev-dependencies]
anyhow = "1.0"
prost = "0.13.1"
prost-build = "0.13.1"

[[test]]
name = "it"
path = "tests/it/main.rs"


[build-dependencies]
glob = "0.3.1"
prost-reflect = "0.14.0"
quote = "1.0.36"
proc-macro2 = "1.0.86"
prettyplease = "0.2.20"
syn = "2.0.70"
